### ISSUE TITLE
java.net.UnknownHostException: Unable to resolve host "wheelmap.org": No address associated with hostname

### ISSUE THREAD

**Issue by christoph-buente** [sozialhelden/wheelmap-android#24]
``` bash
org.springframework.web.client.ResourceAccessException: I/O error: Unable to resolve host "wheelmap.org": No address associated with hostname; nested exception is java.net.UnknownHostException: Unable to resolve host "wheelmap.org": No address associated with hostname
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:491)
at org.wheelmap.android.net.request.RestTemplateExt.doExecute(RestTemplateExt.java:43)
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:453)
at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:251)
at org.wheelmap.android.net.request.RequestProcessor.get(RequestProcessor.java:84)
at org.wheelmap.android.net.AbstractExecutor.executeRequest(AbstractExecutor.java:232)
at org.wheelmap.android.net.SinglePageExecutor.executeSingleRequest(SinglePageExecutor.java:68)
at org.wheelmap.android.net.MultiPageExecutor.executeSingleRequest(MultiPageExecutor.java:44)
at org.wheelmap.android.net.MultiPageExecutor.retrieveMaxNPages(MultiPageExecutor.java:61)
at org.wheelmap.android.net.PhotosExecutor.execute(PhotosExecutor.java:70)
at org.wheelmap.android.service.RestService.onHandleIntent(RestService.java:105)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.net.UnknownHostException: Unable to resolve host "wheelmap.org": No address associated with hostname
at java.net.InetAddress.lookupHostByName(InetAddress.java:394)
at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
at java.net.InetAddress.getAllByName(InetAddress.java:214)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:137)
at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:83)
at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:46)
at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:63)
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:476)
... 14 more
org.springframework.web.client.ResourceAccessException: I/O error: Unable to resolve host "wheelmap.org": No address associated with hostname; nested exception is java.net.UnknownHostException: Unable to resolve host "wheelmap.org": No address associated with hostname
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:491)
at org.wheelmap.android.net.request.RestTemplateExt.doExecute(RestTemplateExt.java:43)
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:453)
at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:251)
at org.wheelmap.android.net.request.RequestProcessor.get(RequestProcessor.java:84)
at org.wheelmap.android.net.AbstractExecutor.executeRequest(AbstractExecutor.java:232)
at org.wheelmap.android.net.SinglePageExecutor.executeSingleRequest(SinglePageExecutor.java:68)
at org.wheelmap.android.net.MultiPageExecutor.executeSingleRequest(MultiPageExecutor.java:44)
at org.wheelmap.android.net.MultiPageExecutor.retrieveMaxNPages(MultiPageExecutor.java:61)
at org.wheelmap.android.net.PhotosExecutor.execute(PhotosExecutor.java:70)
at org.wheelmap.android.service.RestService.onHandleIntent(RestService.java:105)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.net.UnknownHostException: Unable to resolve host "wheelmap.org": No address associated with hostname
at java.net.InetAddress.lookupHostByName(InetAddress.java:394)
at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
at java.net.InetAddress.getAllByName(InetAddress.java:214)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:137)
at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:83)
at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:46)
at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:63)
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:476)
... 14 more

```

**Comment by bushuaigege** [comment]
Problem solved?Please tell me the solution

**Comment by Hoverbear** [comment]
@bushuaigege Wheelmap may have been temporarily down. Please give it another shot?

**Comment by bushuaigege** [comment]
> Don't understand what you mean
