### ISSUE TITLE
libcore.io.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)

### ISSUE THREAD

**Issue by christoph-buente** [sozialhelden/wheelmap-android#26]
``` bash
org.springframework.web.client.ResourceAccessException: I/O error: Connection to http://127.0.0.1:3128 refused; nested exception is org.apache.http.conn.HttpHostConnectException: Connection to http://127.0.0.1:3128 refused
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:491)
at org.wheelmap.android.net.request.RestTemplateExt.doExecute(RestTemplateExt.java:43)
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:453)
at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:251)
at org.wheelmap.android.net.request.RequestProcessor.get(RequestProcessor.java:84)
at org.wheelmap.android.net.AbstractExecutor.executeRequest(AbstractExecutor.java:232)
at org.wheelmap.android.net.SinglePageExecutor.executeSingleRequest(SinglePageExecutor.java:68)
at org.wheelmap.android.net.SinglePageExecutor.retrieveSinglePage(SinglePageExecutor.java:60)
at org.wheelmap.android.net.LocalesExecutor.execute(LocalesExecutor.java:62)
at org.wheelmap.android.service.RestService.onHandleIntent(RestService.java:105)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:176)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: org.apache.http.conn.HttpHostConnectException: Connection to http://127.0.0.1:3128 refused
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:183)
at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:670)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:509)
at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:83)
at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:46)
at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:63)
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:476)
... 13 more
Caused by: java.net.ConnectException: failed to connect to /127.0.0.1 (port 3128) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)
at libcore.io.IoBridge.isConnected(IoBridge.java:223)
at libcore.io.IoBridge.connectErrno(IoBridge.java:161)
at libcore.io.IoBridge.connect(IoBridge.java:112)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
at java.net.Socket.connect(Socket.java:842)
at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
... 22 more
Caused by: libcore.io.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
at libcore.io.IoBridge.isConnected(IoBridge.java:208)
... 29 more
org.springframework.web.client.ResourceAccessException: I/O error: Connection to http://127.0.0.1:3128 refused; nested exception is org.apache.http.conn.HttpHostConnectException: Connection to http://127.0.0.1:3128 refused
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:491)
at org.wheelmap.android.net.request.RestTemplateExt.doExecute(RestTemplateExt.java:43)
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:453)
at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:251)
at org.wheelmap.android.net.request.RequestProcessor.get(RequestProcessor.java:84)
at org.wheelmap.android.net.AbstractExecutor.executeRequest(AbstractExecutor.java:232)
at org.wheelmap.android.net.SinglePageExecutor.executeSingleRequest(SinglePageExecutor.java:68)
at org.wheelmap.android.net.SinglePageExecutor.retrieveSinglePage(SinglePageExecutor.java:60)
at org.wheelmap.android.net.LocalesExecutor.execute(LocalesExecutor.java:62)
at org.wheelmap.android.service.RestService.onHandleIntent(RestService.java:105)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:176)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: org.apache.http.conn.HttpHostConnectException: Connection to http://127.0.0.1:3128 refused
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:183)
at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:670)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:509)
at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:83)
at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:46)
at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:63)
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:476)
... 13 more
Caused by: java.net.ConnectException: failed to connect to /127.0.0.1 (port 3128) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)
at libcore.io.IoBridge.isConnected(IoBridge.java:223)
at libcore.io.IoBridge.connectErrno(IoBridge.java:161)
at libcore.io.IoBridge.connect(IoBridge.java:112)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
at java.net.Socket.connect(Socket.java:842)
at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
... 22 more
Caused by: libcore.io.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
at libcore.io.IoBridge.isConnected(IoBridge.java:208)
... 29 more

```

**Comment by hardslk** [comment]
same issue
