### ISSUE TITLE
org.springframework.web.client.HttpClientErrorException: 400 Bad Request

### ISSUE THREAD

**Issue by christoph-buente** [sozialhelden/wheelmap-android#40]
``` bash
org.springframework.web.client.HttpClientErrorException: 400 Bad Request
at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:76)
at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:524)
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:481)
at org.wheelmap.android.net.request.RestTemplateExt.doExecute(RestTemplateExt.java:43)
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:453)
at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:332)
at org.wheelmap.android.net.request.RequestProcessor.post(RequestProcessor.java:90)
at org.wheelmap.android.net.AbstractExecutor.executeRequest(AbstractExecutor.java:235)
at org.wheelmap.android.net.NodeUpdateOrNewExecutor.execute(NodeUpdateOrNewExecutor.java:103)
at org.wheelmap.android.service.RestService.onHandleIntent(RestService.java:105)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:137)
at android.os.HandlerThread.run(HandlerThread.java:61)
org.springframework.web.client.HttpClientErrorException: 400 Bad Request
at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:76)
at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:524)
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:481)
at org.wheelmap.android.net.request.RestTemplateExt.doExecute(RestTemplateExt.java:43)
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:453)
at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:332)
at org.wheelmap.android.net.request.RequestProcessor.post(RequestProcessor.java:90)
at org.wheelmap.android.net.AbstractExecutor.executeRequest(AbstractExecutor.java:235)
at org.wheelmap.android.net.NodeUpdateOrNewExecutor.execute(NodeUpdateOrNewExecutor.java:103)
at org.wheelmap.android.service.RestService.onHandleIntent(RestService.java:105)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:137)
at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by yichunzhao** [comment]
How you solved this issue? Many thanks

**Comment by gitish** [comment]
did you find any fix for this.. I am facing the same here

**Comment by StayHungryStayFoolish** [comment]
I am facing the same here

**Comment by Ankitwoocation** [comment]
anyone solved this issue?

**Comment by opyh** [comment]
We're about to release a new Android app version – if you want to have a preview, you can get it by opening this link on your Android phone: https://play.google.com/apps/testing/org.wheelmap.android.online
