### ISSUE TITLE
android.database.StaleDataException: Attempting to access a closed CursorWindow.Most probable cause: cursor is deactivated prior to calling this method.

### ISSUE THREAD

**Issue by christoph-buente** [sozialhelden/wheelmap-android#52]
``` bash
android.database.StaleDataException: Attempting to access a closed CursorWindow.Most probable cause: cursor is deactivated prior to calling this method.
at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java)
at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java)
at android.database.CursorWrapper.getLong(CursorWrapper.java)
at org.wheelmap.android.model.POIHelper.getId(POIHelper.java:121)
at org.wheelmap.android.fragment.POIDetailFragment.load(POIDetailFragment.java:968)
at org.wheelmap.android.async.UploadPhotoTask.onPostExecute(UploadPhotoTask.java:98)
at org.wheelmap.android.async.UploadPhotoTask.onPostExecute(UploadPhotoTask.java:29)
at android.os.AsyncTask.finish(AsyncTask.java)
at android.os.AsyncTask.access$600(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java)
at android.os.Handler.dispatchMessage(Handler.java)
at android.os.Looper.loop(Looper.java)
at android.app.ActivityThread.main(ActivityThread.java)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
at dalvik.system.NativeStart.main(Native Method)

```

**Comment by mikedream89** [comment]
hi ,do you find soloution? Can you tell me? 
thanks
