### ISSUE TITLE
Problem while executing

### ISSUE THREAD

**Issue by Myhalva** [sozialhelden/wheelmap-android#57]
i have a issue while load lustview with Locations:

 org.wheelmap.android.service.SyncServiceException: org.springframework.web.client.ResourceAccessException: I/O error: Unrecognized field "wheelchair_toilet" (Class wheelmap.org.domain.node.Node), not marked as ignorable
            at [Source: org.apache.http.conn.EofSensorInputStream@b2504328; line: 1, column: 280] (through reference chain: wheelmap.org.domain.node.Nodes["nodes"]->wheelmap.org.domain.node.Node["wheelchair_toilet"]); nested exception is org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "wheelchair_toilet" (Class wheelmap.org.domain.node.Node), not marked as ignorable
            at [Source: org.apache.http.conn.EofSensorInputStream@b2504328; line: 1, column: 280] (through reference chain: wheelmap.org.domain.node.Nodes["nodes"]->wheelmap.org.domain.node.Node["wheelchair_toilet"])
            at org.wheelmap.android.net.BaseRetrieveExecutor.retrieveNumberOfHits(BaseRetrieveExecutor.java:134)
            at org.wheelmap.android.net.BaseRetrieveExecutor.executeSingleRequest(BaseRetrieveExecutor.java:94)
            at org.wheelmap.android.net.BaseRetrieveExecutor.retrieveMaxNPages(BaseRetrieveExecutor.java:73)
            at org.wheelmap.android.net.NodesExecutor.execute(NodesExecutor.java:122)
            at org.wheelmap.android.service.SyncService.onHandleIntent(SyncService.java:127)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: org.springframework.web.client.ResourceAccessException: I/O error: Unrecognized field "wheelchair_toilet" (Class wheelmap.org.domain.node.Node), not marked as ignorable
            at [Source: org.apache.http.conn.EofSensorInputStream@b2504328; line: 1, column: 280] (through reference chain: wheelmap.org.domain.node.Nodes["nodes"]->wheelmap.org.domain.node.Node["wheelchair_toilet"]); nested exception is org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "wheelchair_toilet" (Class wheelmap.org.domain.node.Node), not marked as ignorable
            at [Source: org.apache.http.conn.EofSensorInputStream@b2504328; line: 1, column: 280] (through reference chain: wheelmap.org.domain.node.Nodes["nodes"]->wheelmap.org.domain.node.Node["wheelchair_toilet"])
            at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:466)
            at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:428)
            at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:226)
            at wheelmap.org.request.RequestProcessor.get(RequestProcessor.java:45)
            at org.wheelmap.android.net.BaseRetrieveExecutor.retrieveNumberOfHits(BaseRetrieveExecutor.java:119)
            at org.wheelmap.android.net.BaseRetrieveExecutor.executeSingleRequest(BaseRetrieveExecutor.java:94)
            at org.wheelmap.android.net.BaseRetrieveExecutor.retrieveMaxNPages(BaseRetrieveExecutor.java:73)
            at org.wheelmap.android.net.NodesExecutor.execute(NodesExecutor.java:122)
            at org.wheelmap.android.service.SyncService.onHandleIntent(SyncService.java:127)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "wheelchair_toilet" (Class wheelmap.org.domain.node.Node), not marked as ignorable
            at [Source: org.apache.http.conn.EofSensorInputStream@b2504328; line: 1, column: 280] (through reference chain: wheelmap.org.domain.node.Nodes["nodes"]->wheelmap.org.domain.node.Node["wheelchair_toilet"])
            at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownFieldException(StdDeserializationContext.java:246)
            at org.codehaus.jackson.map.deser.StdDeserializer.reportUnknownProperty(StdDeserializer.java:604)
            at org.codehaus.jackson.map.deser.StdDeserializer.handleUnknownProperty(StdDeserializer.java:590)
            at org.codehaus.jackson.map.deser.BeanDeserializer.handleUnknownProperty(BeanDeserializer.java:689)
            at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:514)
            at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:350)
            at org.codehaus.jackson.map.deser.CollectionDeserializer.deserialize(CollectionDeserializer.java:120)
            at org.codehaus.jackson.map.deser.CollectionDeserializer.deserialize(CollectionDeserializer.java:97)
            at org.codehaus.jackson.map.deser.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
            at org.codehaus.jackson.

**Comment by christoph-buente** [comment]
Hi @Myhalva 

thx for this issue. "wheelchair_toilet" is a new field we added to the API in preparation of a new feature. We tested it with the latest wheelmap version from android store and it worked fine.

There two things you could do. Either set this field to ignorable or extend the Node Model to save this wheelchair_toilet with values with "yes" or "no".

Any pull request is welcome.

Cheers, Christoph

**Comment by Myhalva** [comment]
WOW greath thanks you save my life!!!

i added:
    String wheelchair_toilet;
    public String getWheelchair_toilet() {
        return wheelchair_toilet;
    }


    public void setWheelchair_toilet(String value) {
        this.wheelchair_toilet = "yes";
    }


.... and to the Node String

", wheelchair_toilet="+wheelchair_toilet +

**Comment by christoph-buente** [comment]
Feel free to submit a pull request with your changes and some test code.
